In [349]:
import torch
import numpy as np

In [350]:
batch_size = 2
y_pred = torch.rand(batch_size,6,9,16)
y_true = torch.zeros(batch_size,6,9,16)
y_true[:,:, 3,9] = torch.tensor([1.0, 0.6, 0.4, 0.03, 0.04, 1.0])
# y_true[:,6,4,:] = torch.tensor([1.0, 0.3, 0.7, 0.08, 0.09, 1.0]) 

In [359]:
bb_loc = (y_true[:, 0] == 1.0).unsqueeze(1).repeat(1,6,1,1)
bb_nloc = (y_true[:, 0] == 0.0).unsqueeze(1).repeat(1,6,1,1)
print(bb_loc.shape)
print(bb_nloc.shape)
y_pred_bb = y_pred[bb_loc]
y_true_bb = y_true[bb_loc]
y_pred_nbb = y_pred[bb_nloc]
y_true_nbb = y_true[bb_nloc]
print(y_pred_bb)
print(y_pred_bb.shape)
print(y_true_bb.shape)
print(y_pred_nbb.shape)
print(y_true_nbb.shape)

torch.Size([2, 6, 9, 16])
torch.Size([2, 6, 9, 16])
tensor([0.3008, 0.1688, 0.7941, 0.2937, 0.0686, 0.0192, 0.3788, 0.3652, 0.9513,
        0.8604, 0.9905, 0.5022])
torch.Size([12])
torch.Size([12])
torch.Size([1716])
torch.Size([1716])


In [236]:
mid1 = (y_true_bb[:,5].squeeze() - y_pred_bb[:,5].squeeze())
mid2 = mid1 ** 2.0
mid3 = mid2.sum() / batch_size
out = ((y_true_bb[:,5].squeeze() - y_pred_bb[:,5].squeeze()) ** 2.0).sum() / batch_size

In [237]:
print("Classification loss: ")
print(y_true_bb[:, 5])
print(y_pred_bb[:, 5])
print(mid1)
print(mid2)
print(mid3)
print(out)

Classification loss: 
tensor([1., 1.])
tensor([0.3471, 0.0037])
tensor([0.6529, 0.9963])
tensor([0.4263, 0.9926])
tensor(0.7094)
tensor(0.7094)


In [238]:
mid1_1 = (y_true_bb[:, 1].squeeze() - y_pred_bb[:, 1].squeeze()) ** 2.0
mid1_2 = (y_true_bb[:, 2].squeeze() - y_pred_bb[:, 2].squeeze()) ** 2.0
mid1_3 = (y_true_bb[:, 3].sqrt().squeeze() - y_pred_bb[:, 3].sqrt().squeeze()) ** 2.0
mid1_4 = (y_true_bb[:, 4].sqrt().squeeze() - y_pred_bb[:, 4].sqrt().squeeze()) ** 2.0
mid2_1 = mid1_1 + mid1_2
mid2_2 = mid1_3 + mid1_4
mid3_1 = mid2_1.sum()
mid3_2 = mid2_2.sum()
mid4 = mid3_1 + mid3_2 / batch_size
out = ((((y_true_bb[:, 1].squeeze() - y_pred_bb[:, 1].squeeze()) ** 2.0) + ((y_true_bb[:, 2].squeeze() - y_pred_bb[:, 2].squeeze()) ** 2.0)).sum(
        ) + (((y_true_bb[:, 3].sqrt().squeeze() - y_pred_bb[:, 3].sqrt().squeeze()) ** 2.0) + ((y_true_bb[:, 4].sqrt().squeeze() - y_pred_bb[:, 4].sqrt().squeeze()) ** 2.0)).sum()) / batch_size

In [239]:
print("Localization loss: ")
print(y_true_bb[:, 1:5])
print(y_pred_bb[:, 1:5])
print(mid1_1)
print(mid1_2)
print(mid1_3)
print(mid1_4)
print(mid2_1)
print(mid2_2)
print(mid3_1)
print(mid3_2)
print(mid4)
print(out)

Localization loss: 
tensor([[0.6000, 0.4000, 0.0300, 0.0400],
        [0.6000, 0.4000, 0.0300, 0.0400]])
tensor([[0.9626, 0.1525, 0.7797, 0.3456],
        [0.5969, 0.9633, 0.4568, 0.2057]])
tensor([1.3149e-01, 9.3661e-06])
tensor([0.0613, 0.3173])
tensor([0.5038, 0.2527])
tensor([0.1505, 0.0643])
tensor([0.1928, 0.3173])
tensor([0.6543, 0.3170])
tensor(0.5101)
tensor(0.9713)
tensor(0.9957)
tensor(0.7407)


In [240]:
mid1_1 = (y_true_bb[:,0].squeeze() - y_pred_bb[:,0].squeeze())
mid1_2 = (y_true_nbb[:,0].squeeze() - y_pred_nbb[:,0].squeeze())
mid2_1 = mid1_1 ** 2.0
mid2_2 = mid1_2 ** 2.0
mid3_1 = mid2_1.sum()
mid3_2 = mid2_2.sum()
mid4 = mid3_1 + mid3_2 / batch_size
out = (((y_true_bb[:,0].squeeze() - y_pred_bb[:,0].squeeze()) ** 2.0).sum()) + (((y_true_nbb[:,0].squeeze() - y_pred_nbb[:,0].squeeze()) ** 2.0).sum()) / batch_size

In [241]:
print("Confidence loss: ")
print(y_true_bb[:, 0])
print(y_pred_bb[:, 0])
print(y_true_nbb[:, 0])
print(y_pred_nbb[:, 0])
print(mid1_1)
print(mid1_2)
print(mid2_1)
print(mid2_2)
print(mid3_1)
print(mid3_2)
print(mid4)
print(out)

Confidence loss: 
tensor([1., 1.])
tensor([0.8261, 0.4755])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    

In [344]:
true_idx = y_true[:,:,:,0].view(y_true[:,:,:,0].size(0), -1).max(dim=-1).indices
true_y, true_x = torch.tensor(np.unravel_index(true_idx, y_true[:,:,:,0].shape))[1:3]
pred_idx = y_pred[:,:,:,0].view(y_pred[:,:,:,0].size(0), -1).max(dim=-1).indices
pred_y, pred_x = torch.tensor(np.unravel_index(pred_idx, y_pred[:,:,:,0].shape))[1:3]
print(true_y, true_x)
print(pred_y, pred_x)
print()
y_true_bb = torch.stack([bb[true_y[i], true_x[i], 1:5] for i, bb in enumerate(y_true)],1)
y_pred_bb = torch.stack([bb[pred_y[i], pred_x[i], 1:5] for i, bb in enumerate(y_pred)],1)
print(y_true_bb)
print(y_pred_bb)
print()


tensor([3, 3]) tensor([9, 9])
tensor([7, 7]) tensor([12,  4])

tensor([[0.6000, 0.6000],
        [0.4000, 0.4000],
        [0.0300, 0.0300],
        [0.0400, 0.0400]])
tensor([[0.1429, 0.6819],
        [0.4868, 0.4997],
        [0.8284, 0.6458],
        [0.7096, 0.4632]])



In [347]:
true_bb = torch.stack([torch.max(y_true_bb[0]-(y_true_bb[2]/2), torch.tensor(0.0)),
           torch.max(y_true_bb[1]-(y_true_bb[3]/2), torch.tensor(0.0)),
           torch.min(y_true_bb[0]+(y_true_bb[2]/2), torch.tensor(1.0)),
           torch.min(y_true_bb[1]+(y_true_bb[3]/2), torch.tensor(1.0))])
print(true_bb)
pred_bb = torch.stack([torch.max(y_pred_bb[0]-(y_pred_bb[2]/2), torch.tensor(0.0)),
           torch.max(y_pred_bb[1]-(y_pred_bb[3]/2), torch.tensor(0.0)),
           torch.min(y_pred_bb[0]+(y_pred_bb[2]/2), torch.tensor(1.0)),
           torch.min(y_pred_bb[1]+(y_pred_bb[3]/2), torch.tensor(1.0))])
print(pred_bb)
inter_bb = torch.stack([torch.max(true_bb[0], pred_bb[0]),
                        torch.max(true_bb[1], pred_bb[1]),
                        torch.min(true_bb[2], pred_bb[2]),
                        torch.min(true_bb[3], pred_bb[3])])
print(inter_bb)
# calculate IoU
true_area = y_true_bb[2]*y_true_bb[3]
print(true_area)
pred_area = y_pred_bb[2]*y_pred_bb[3]
print(pred_area)
inter_area = torch.max(inter_bb[2]-inter_bb[0], torch.tensor(0.0)) * torch.max(inter_bb[3]-inter_bb[1], torch.tensor(0.0))
print(inter_area)
iou = inter_area / (true_area + pred_area - inter_area)
print(iou)

tensor([[0.5850, 0.5850],
        [0.3800, 0.3800],
        [0.6150, 0.6150],
        [0.4200, 0.4200]])
tensor([[0.0000, 0.3590],
        [0.1319, 0.2681],
        [0.5571, 1.0000],
        [0.8416, 0.7313]])
tensor([[0.5850, 0.5850],
        [0.3800, 0.3800],
        [0.5571, 0.6150],
        [0.4200, 0.4200]])
tensor([0.0012, 0.0012])
tensor([0.5878, 0.2991])
tensor([0.0000, 0.0012])
tensor([0.0000, 0.0040])
